// Generated by gencpp from file opencvyi/position.msg
// DO NOT EDIT!


#ifndef OPENCVYI_MESSAGE_POSITION_H
#define OPENCVYI_MESSAGE_POSITION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace opencvyi
{
template <class ContainerAllocator>
struct position_
{
  typedef position_<ContainerAllocator> Type;

  position_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , Flag(0)  {
    }
  position_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , Flag(0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef int32_t _Flag_type;
  _Flag_type Flag;





  typedef boost::shared_ptr< ::opencvyi::position_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::opencvyi::position_<ContainerAllocator> const> ConstPtr;

}; // struct position_

typedef ::opencvyi::position_<std::allocator<void> > position;

typedef boost::shared_ptr< ::opencvyi::position > positionPtr;
typedef boost::shared_ptr< ::opencvyi::position const> positionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::opencvyi::position_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::opencvyi::position_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace opencvyi

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'opencvyi': ['/home/cuicheng/work/src/opencvyi/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::opencvyi::position_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::opencvyi::position_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::opencvyi::position_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::opencvyi::position_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::opencvyi::position_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::opencvyi::position_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::opencvyi::position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0ae3a5e6ef89db379797fe438faae530";
  }

  static const char* value(const ::opencvyi::position_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0ae3a5e6ef89db37ULL;
  static const uint64_t static_value2 = 0x9797fe438faae530ULL;
};

template<class ContainerAllocator>
struct DataType< ::opencvyi::position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "opencvyi/position";
  }

  static const char* value(const ::opencvyi::position_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::opencvyi::position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n\
float64 y\n\
float64 z\n\
int32 Flag\n\
";
  }

  static const char* value(const ::opencvyi::position_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::opencvyi::position_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.Flag);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct position_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::opencvyi::position_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::opencvyi::position_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "Flag: ";
    Printer<int32_t>::stream(s, indent + "  ", v.Flag);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPENCVYI_MESSAGE_POSITION_H
